frontend/.gitignore
frontend/README.md
frontend/package.json
frontend/public/index.html
frontend/src/App.js
frontend/src/index.css
frontend/src/index.js

This is the folder that the different tracks will use to code

created folder for the different tracks

---

app.js
controllers/sidebarController.js
data/sidebarData.json
routes/sidebarRoute.js

For now, i filled the sidebar data with dummy texts so i could quickly set up the routing.

Feat: Sidebar controller & route

---

models/goal.model.js
package-lock.json
package.json
yarn.lock

Created a new mongoose schema for the goals model.

---

data/sidebarData.json

Feat: Sidebar options with image links

---

app.js
data/pluginInfo.json

Replace former fields and dummy data entries with correct fields and information respectively.
refs #359, resolves #329

refactor(pluginInfo): Update JSON fields and entries

---

controllers/goalController.js
package.json
yarn.lock

Added controller for getting single goals
#333

added single goal controller

---

client/src/components/mainside/Mainside.jsx

I donno who removed the button but it has to be there

Readded the edit modal button

---

schemas/goal.schema.js

Created schema directory and added goals schema.

---

controllers/goalController.js
myapp/package-lock.json
routes/goalRoutes.js

added a create goal route

---

routes/goalRoutes.js

Create a route to get a single goal

---

controllers/goalController.js
routes/goalRoutes.js

updated single goal controller and fixed conflicts

updated single goal controller with zuri core

---

controllers/goalController.js

fix(goalController): return status and message

---

client/src/components/Modal/EditMisssion.jsx
client/src/pages/Home.jsx

Created a new edit mission modal

New Edit Mission Modal

---

client/src/components/header/Header.jsx
client/src/pages/Home.jsx

Reverts zurichat/zc_plugin_company_goals#531

Revert "updated repo"

---

routes/goalRoutes.js

issue #335 ]
Test: https://goals.zuri.chat/api/v1/goals/update/612e42849f34172f0cac4026
The ID for the goal you intend to update the details.
The test returns a "success" response if successful.

feat: added updateGoalByID function and route

---

routes/goalRoutes.js

To test: https://goals.zuri.chat/api/v1/update/612e42849f34172f0cac4026
issue #335
The ID is for the goal to be updated with a payload.

feat: created updateGoalByID controller

---

controllers/visionController.js

Kelvin please test and let me know

Added controller logic for createVision 

---

client/src/components/Searchinteractive/SearchInteractive.js
client/src/components/Searchinteractive/SearchInteractive.styled.js
client/src/components/navbar/Navbar.jsx

This pull request closes issue #607
Click on search input on [goals.zuri.chat](goals.zuri.chat) and a search interactive appears

Display search interactive

---

client/src/components/Notification/Notification.jsx
client/src/components/Notification/styledNotification.js
client/src/components/goal interface navbar/NavLayout.js

Mark all as read remove all dummy notifications data.

Added Mark All As Read Functionality

---

controllers/roomController.js
controllers/sidebarController.js
db/databaseHelper.js

- Add code to validate that room id is valid
- That user cannot join same room multiple times

Validation and bugfixes

---

client/src/components/Dropdown/Design.js
client/src/components/Dropdown/MenuOption.js
client/src/components/Dropdown/Mobile.js
client/src/components/Dropdown/MobilePrivate.js

These are dropdown features of the goal menu, sort by option  and mobile

adding the dropdown feature

---

controllers/sidebarController.js
routes/sidebarRoute.js

I left comments on the logic of the sidebar controller and i created a dummy user with the id of 002, to test the sidebar endpoint. I made the dummy user join three rooms which you will see when you test the endpoint. Furthermore, if a user has not joined a room, i set up an error message to be sent back as a response. 
test the sidebar of the dummy user on localhost: localhost:4000/api/v1/sidebar?user=002&org=1
to test the sidebar of the user that hasn't joined any room, change the user id to a random one. Hopefully, when the auth middleware is completed, verifying the user token before returning the sidebar for the user will be implemented.
Soon, i'll figure out the logic for public rooms :)

Sidebar Endpoint

---

controllers/roomController.js
controllers/sidebarController.js

- Ensured we search for only rooms in that organization. 
- Added organization_id to all queries as it will be important when working with the actua zuri core api

feat: minor changes to the sidebar and create room endpoint

---

schemas/index.js

Refactored the goal schema. i am still working on the create goal controller and adding users to the goal since we've established that each goal is a room.

refactor(BE): GoalSchema

---

controllers/missionController.js

- Endpoint to get mission is it exists. 
- If it doesn't exist it created a mission as an empty string so it can be updated.

add code to get mission

---

controllers/goalController.js
controllers/sidebarController.js
db/databaseHelper.js
utils/config.js

Hi, i worked on the create goals endpoint and the get all goals endpoint. As well as getting a single goal.

Create goals & get goals

---

app.js
controllers/infoController.js
controllers/missionController.js
controllers/visionController.js
routes/goalRoutes.js
routes/missionRoute.js
routes/visionRoutes.js

- I implemented the update vision endpoint using the fake API
- It does not work yet, as it depends on the existence of a vision collection
- Prone to several refactors once validation middleware is implemented

#694 Implement Preliminary Update Vision Endpoint

---

client/src/components/modal/EditMission.jsx
client/src/pages/Home.jsx

- Resolved issues where react app didn't build on Linux environment due to issues with imports.

resolved build issues

---

controllers/missionController.js
routes/missionRoute.js

Created endpoint to update mission statement

---

controllers/missionController.js
db/databaseHelper.js
routes/missionRoute.js

- fix bugs using the update one helper.

fix minor bugs in mission endpoint

---

client/src/components/mainside/Mainside.jsx
client/src/components/modal/EditMission.jsx
client/src/pages/Home.jsx

- Resolved some issues with imports and modules in the react app

resolve build issues in react app

---

middlewares/validate.js

* I refactored the auth middleware to retrieve the bearer token
from the request headers, and call the verification endpoint on
zcore.
* I also attached some role assignment logic, for testing purposes.
refs #656

Refactor Auth Validation Middleware

---

client/public/index.html
client/src/components/mainside/Mainside.jsx
client/src/components/modal/ExportReport.jsx
client/src/pages/Home.jsx

trying to resolve secured connection issues with zuri websocket server

add meta tag for wss connection - 1

---

controllers/goalController.js
routes/goalRoutes.js
schemas/index.js

Adding and removing likes
Getting all goal likes
Checking the like status of a user for a particular goal

Goal likes

---

controllers/goalController.js
db/databaseHelper.js
routes/goalRoutes.js
schemas/index.js
utils/config.js

Hi, i changed the create goal schema to fit into the new design.
Also, i created a function to assign users to a goal, remove users from a goal, and delete records of assigned users to goals when a goal is deleted.

New goal schema

---

controllers/goalController.js
db/databaseHelper.js
routes/goalRoutes.js
utils/config.js

Heyy, so i added the function to assign goals to users, remove users from assigned list and delete assigned users when a goal is deleted

Assign goals & remove assignees

---

controllers/goalController.js
schemas/index.js

Hi, i left out some things in the schema remake. kindly review updated version.

!refactor(BE): goal schema

---

controllers/goalController.js
controllers/missionController.js
controllers/visionController.js
routes/missionRoute.js

- Remove middlewares from mission endpoint
- Fix minor bugs in centrifugo

Bug fixes and code refactor

---

client/src/components/DeleteError/DeleteErrorAsset/Error.svg
client/src/components/DeleteError/DeleteErrorModal.js
client/src/components/DeleteError/deleteError.js
client/src/pages/Home.jsx

To contribute to the workflow, I created a delete Error modal

Created the Delete Error Modal

---

controllers/goalController.js
schemas/index.js

So i was thinking, security wise, it's unsafe to add the org id to the goal data. My mistake.

fix(BE): removed org_id from the goal data

---

client/src/components/organization_vision/org_display_vision/VisionDisplay.jsx
client/src/components/organization_vision/org_edit_vision/modal/EditOrgVisionModal.jsx

this PR makes the UI reflect the edited vision reflect immediately without a reload

final  on the edit vision UI

---

app.js
controllers/searchController.js
routes/searchRoute.js
utils/Directory.js

Search file , User can be able to search file uploaded to channelSearch file , User can be able to search file uploaded to channel

Search file , User can be able to search file uploaded to channel

---

controllers/goalController.js

Also created a check for non-existing goal ids. Kindly review.

refactor(BE): made check for null goal value

---

client/src/components/Modal/ExportModal/ExportButton.jsx
client/src/components/Modal/ExportModal/ExportReport.jsx
client/src/components/Modal/ExportModal/GoalFolder.jsx
client/src/components/Modal/ExportModal/ReportFormat.jsx
client/src/components/Modal/ExportModal/ReportType.jsx
package.json

The function checks whether the user needs the goal data downloaded as PDF or Excel Spreadsheet file.

Download Export - SpreadSheet Functionality

---

client/src/components/Deletemodal/Deletemodal.js
client/src/components/Goals/GoalDropDown.js
client/src/components/Goals/GoalItem.jsx
client/src/components/Goals/GoalItem.style.js

The delete function is now working.
GoalDropdown repositioned

Delete functionality implemented

---

client/src/components/Goals/GoalItem.jsx
client/src/components/Goals/GoalItem.style.js

Responsiveness for goals fix

---

controllers/goalController.js

Hi kindly review new start and due date validation

fix(BE): Start and due dates validation

---

client/src/components/Modal/styledEditMission.js
client/src/components/organization_vision/org_edit_vision/modal/EditOrgVision.styled.js

Fix edit mission and vision modal design

---

client/src/components/Goals/GoalDropDown.js
client/src/components/Goals/GoalItem.jsx
client/src/components/Goals/GoalItem.style.js

Improved the goal drop down UI & toggleChange function

---

client/src/components/Notification/styledNotification.js

Fix Pagination Styling on Notifications

---

app.js
controllers/goalController.js
controllers/targetController.js
routes/goalRoutes.js

You introduced unwanted changes, that had been removed in a prior commit.

Revert "Added the progress to each goal"

---

controllers/goalController.js
schemas/index.js

Fix(update goal):  fixed wrong fields update by validating the incoming req body against allowed fields

---

client/src/components/GoalDetailAccordion/GoalDetails.jsx
client/src/components/reports_and_notifications/ReportsAndNotificationContainer.jsx
client/src/redux/notificationSlice.js

The Org-id to get notifications have been made dynamic

Dynmaic OrgId to get notifications

---

client/src/components/GoalDetailAccordion/QuaterlyGoal.js

FILTER FOR QUATERLY GOAL

---

client/src/components/organization_mission_vision_display/MissionVisionDisplay.styled.js

Fix/mission vision UI

---

client/src/components/Goals/GoalItem.jsx
client/src/components/Goals/GoalItem.style.js

change the goal title text color to red when the goal is expired

change the goal title text when the goal is expired

---

client/src/components/goal_interface_inner_header/InnerNav.js

Use dynamic org for the API call

---

client/src/components/Goals/GoalItem.jsx

Called my api in a use effect as my fe wasnt available to do it

Called my api in a use effect

---

controllers/cronController.js

My cronjob is now running every Minute

Cronjob now runnig every minute.

---

controllers/BsearchController.js
test/bsearch/index.html

Added search by description, view all goals on test page, and submitting search with enter.

Added search by description, view all goals on test page, and submitting search with enter.

---

controllers/PluginController.js
services/plugin.service.js

Hi, i realized there were some promise rejections and responses i didn't properly handle in the plugin install and uninstall endpoints. This PR has a fix to that. kindly review, thank you.

Fix(plugin):  properly handled promise rejections

---

controllers/notificationController.js
services/notification.service.js
test/unit/notification/getNotification.test.js

- notification service was not called properly and caused 500 error in the code

fix: notifications

---

controllers/goalController.js
helpers/response.js

added a response helper file with example usage.

added a response helper file

---

LICENSE

Feat: license 
